/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Fixed */

#ifndef _Included_org_java_gtk_gtk_Fixed
#define _Included_org_java_gtk_gtk_Fixed
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Fixed
 * Method:    gtk_fixed_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Fixed_gtk_1fixed_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_Fixed
 * Method:    gtk_fixed_put
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Fixed_gtk_1fixed_1put
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
