/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Button_ClickedEventHandler */

#ifndef _Included_org_java_gtk_gtk_Button_ClickedEventHandler
#define _Included_org_java_gtk_gtk_Button_ClickedEventHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
