/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_SeparatorToolItem */

#ifndef _Included_org_java_gtk_gtk_SeparatorToolItem
#define _Included_org_java_gtk_gtk_SeparatorToolItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_SeparatorToolItem
 * Method:    gtk_separator_tool_item_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_SeparatorToolItem_gtk_1separator_1tool_1item_1new
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
