/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_TextView */

#ifndef _Included_org_java_gtk_gtk_TextView
#define _Included_org_java_gtk_gtk_TextView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_TextView
 * Method:    gtk_text_view_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_TextView_gtk_1text_1view_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_TextView
 * Method:    gtk_text_view_set_editable
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_TextView_gtk_1text_1view_1set_1editable
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_java_gtk_gtk_TextView
 * Method:    gtk_text_view_get_editable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_1gtk_gtk_TextView_gtk_1text_1view_1get_1editable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_TextView
 * Method:    gtk_text_view_set_cursor_visible
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_TextView_gtk_1text_1view_1set_1cursor_1visible
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_java_gtk_gtk_TextView
 * Method:    gtk_text_view_get_cursor_visible
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_1gtk_gtk_TextView_gtk_1text_1view_1get_1cursor_1visible
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
