/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gdk_Pixbuf */

#ifndef _Included_org_java_gtk_gdk_Pixbuf
#define _Included_org_java_gtk_gdk_Pixbuf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gdk_Pixbuf
 * Method:    gdk_pixbuf_new_from_file
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gdk_Pixbuf_gdk_1pixbuf_1new_1from_1file
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
