/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Gtk */

#ifndef _Included_org_java_gtk_gtk_Gtk
#define _Included_org_java_gtk_gtk_Gtk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Gtk
 * Method:    gtk_init
 * Signature: (Ljava/lang/Object;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Gtk_gtk_1init
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     org_java_gtk_gtk_Gtk
 * Method:    gtk_main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Gtk_gtk_1main
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_Gtk
 * Method:    gtk_main_quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Gtk_gtk_1main_1quit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
