/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_SeparatorMenuItem */

#ifndef _Included_org_java_gtk_gtk_SeparatorMenuItem
#define _Included_org_java_gtk_gtk_SeparatorMenuItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_SeparatorMenuItem
 * Method:    gtk_separator_menu_item_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_SeparatorMenuItem_gtk_1separator_1menu_1item_1new
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
