/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Box */

#ifndef _Included_org_java_gtk_gtk_Box
#define _Included_org_java_gtk_gtk_Box
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Box
 * Method:    gtk_box_new
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Box_gtk_1box_1new
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
