/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Container */

#ifndef _Included_org_java_gtk_gtk_Container
#define _Included_org_java_gtk_gtk_Container
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Container
 * Method:    gtk_container_add
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Container_gtk_1container_1add
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_java_gtk_gtk_Container
 * Method:    gtk_container_set_border_width
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Container_gtk_1container_1set_1border_1width
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_java_gtk_gtk_Container
 * Method:    gtk_container_get_border_width
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_java_1gtk_gtk_Container_gtk_1container_1get_1border_1width
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
