/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gdk_Pixbuf_PixbufError */

#ifndef _Included_org_java_gtk_gdk_Pixbuf_PixbufError
#define _Included_org_java_gtk_gdk_Pixbuf_PixbufError
#ifdef __cplusplus
extern "C" {
#endif
#undef org_java_gtk_gdk_Pixbuf_PixbufError_serialVersionUID
#define org_java_gtk_gdk_Pixbuf_PixbufError_serialVersionUID -3042686055658047285i64
#undef org_java_gtk_gdk_Pixbuf_PixbufError_serialVersionUID
#define org_java_gtk_gdk_Pixbuf_PixbufError_serialVersionUID -3387516993124229948i64
#undef org_java_gtk_gdk_Pixbuf_PixbufError_serialVersionUID
#define org_java_gtk_gdk_Pixbuf_PixbufError_serialVersionUID 1i64
#undef org_java_gtk_gdk_Pixbuf_PixbufError_serialVersionUID
#define org_java_gtk_gdk_Pixbuf_PixbufError_serialVersionUID 1i64
#ifdef __cplusplus
}
#endif
#endif
