/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gobject_GObject */

#ifndef _Included_org_java_gtk_gobject_GObject
#define _Included_org_java_gtk_gobject_GObject
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
