/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Box */

#ifndef _Included_org_java_gtk_gtk_Box
#define _Included_org_java_gtk_gtk_Box
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Box
 * Method:    gtk_box_new
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Box_gtk_1box_1new
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_java_gtk_gtk_Box
 * Method:    gtk_box_set_spacing
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Box_gtk_1box_1set_1spacing
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_java_gtk_gtk_Box
 * Method:    gtk_box_get_spacing
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_java_1gtk_gtk_Box_gtk_1box_1get_1spacing
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_Box
 * Method:    gtk_box_pack_start
 * Signature: (JJZZI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Box_gtk_1box_1pack_1start
  (JNIEnv *, jclass, jlong, jlong, jboolean, jboolean, jint);

/*
 * Class:     org_java_gtk_gtk_Box
 * Method:    gtk_box_pack_end
 * Signature: (JJZZI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Box_gtk_1box_1pack_1end
  (JNIEnv *, jclass, jlong, jlong, jboolean, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
