/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Button */

#ifndef _Included_org_java_gtk_gtk_Button
#define _Included_org_java_gtk_gtk_Button
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Button
 * Method:    gtk_button_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Button_gtk_1button_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_Button
 * Method:    gtk_button_new_with_label
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Button_gtk_1button_1new_1with_1label
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_java_gtk_gtk_Button
 * Method:    gtk_button_new_with_mnemonic
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Button_gtk_1button_1new_1with_1mnemonic
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_java_gtk_gtk_Button
 * Method:    gtk_button_new_from_stock
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Button_gtk_1button_1new_1from_1stock
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_java_gtk_gtk_Button
 * Method:    gtk_button_add_clicked_event_handler
 * Signature: (JLorg/java_gtk/gtk/Button/ClickedEventHandler;Lorg/java_gtk/gtk/Button;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Button_gtk_1button_1add_1clicked_1event_1handler
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     org_java_gtk_gtk_Button
 * Method:    gtk_button_get_label
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_java_1gtk_gtk_Button_gtk_1button_1get_1label
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_Button
 * Method:    gtk_button_set_label
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Button_gtk_1button_1set_1label
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
