/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Window */

#ifndef _Included_org_java_gtk_gtk_Window
#define _Included_org_java_gtk_gtk_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Window
 * Method:    gtk_window_new
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Window_gtk_1window_1new
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_java_gtk_gtk_Window
 * Method:    gtk_window_set_title
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Window_gtk_1window_1set_1title
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_java_gtk_gtk_Window
 * Method:    gtk_window_get_title
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_java_1gtk_gtk_Window_gtk_1window_1get_1title
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
