/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_CheckButton */

#ifndef _Included_org_java_gtk_gtk_CheckButton
#define _Included_org_java_gtk_gtk_CheckButton
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_CheckButton
 * Method:    gtk_check_button_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_CheckButton_gtk_1check_1button_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_CheckButton
 * Method:    gtk_check_button_new_with_label
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_CheckButton_gtk_1check_1button_1new_1with_1label
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_java_gtk_gtk_CheckButton
 * Method:    gtk_check_button_new_with_mnemonic
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_CheckButton_gtk_1check_1button_1new_1with_1mnemonic
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
