/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Widget_ConfigureEventHandler */

#ifndef _Included_org_java_gtk_gtk_Widget_ConfigureEventHandler
#define _Included_org_java_gtk_gtk_Widget_ConfigureEventHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
