/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_cairo_CairoContext */

#ifndef _Included_org_java_gtk_cairo_CairoContext
#define _Included_org_java_gtk_cairo_CairoContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_cairo_CairoContext
 * Method:    cairo_show_text
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_cairo_CairoContext_cairo_1show_1text
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_java_gtk_cairo_CairoContext
 * Method:    cairo_move_to
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_cairo_CairoContext_cairo_1move_1to
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
