/* 
 * Copyright (c) 2012 - 2013, JavaGTK and Bill Hull
 *
 * Permission to use, copy, modify, and/or distribute this software
 * for any purpose with or without fee is hereby granted, provided 
 * that the above copyright notice and this permission notice appear 
 * in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL 
 * WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED 
 * WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE 
 * AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 * DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 
 * OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER 
 * TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR 
 * PERFORMANCE OF THIS SOFTWARE.
 */

package org.java_gtk.gtk;

/**
 * A StatusBar is usually placed along the bottom of an application's main 
 * Window. It may provide a regular commentary of the application's status 
 * (as is usually the case in a web browser, for example), or may be used 
 * to simply output a message when the status changes, (when an upload is 
 * complete in an FTP client, for example). 
 * <p>
 * Status bars in GTK+ maintain a stack of messages. The message at the top 
 * of the each bar's stack is the one that will currently be displayed. 
 * <p>
 * Any messages added to a statusbar's stack must specify a context id that 
 * is used to uniquely identify the source of a message. This context id can 
 * be generated by getContextId(), given a message and the StatusBar that it 
 * will be added to. Note that messages are stored in a stack, and when 
 * choosing which message to display, the stack structure is adhered to, 
 * regardless of the context identifier of a message.
 * 
 * @author Bill
 *
 */
public class StatusBar extends Box {
	
	private static native final long gtk_statusbar_new();
	private static native final int gtk_statusbar_push(long statusbarPointer, int context_id, String text);
	private static native final void gtk_statusbar_pop(long statusbarPointer, int context_id);
	private static native final int gtk_statusbar_get_context_id(long statusbarPointer, String description);

	/**
	 * Constructs a StatusBar.
	 */
	public StatusBar() {
		super(newStatusBar());
	}
	
	private static long newStatusBar() {
		lock.lock();
		try {
			return gtk_statusbar_new();
		}
		finally {
			lock.unlock();
		}
	}

	/**
	 * Pushes a new message onto a StatusBar's stack.
	 * 
	 * @param contextId the message's context id
	 * @param text the message to add to the StatusBar
	 * @return a message id
	 */
	public int push(int contextId, String text) {
		lock.lock();
		try {
			return gtk_statusbar_push(this.pointer, contextId, text);
		}
		finally {
			lock.unlock();
		}
	}
	
	/**
	 * Removes the first message in the StatusBar's stack with the given contextId
	 *  
	 * @param contextId a context id
	 */
	public void pop(int contextId) {
		lock.lock();
		try {
			gtk_statusbar_pop(this.pointer, contextId);
		}
		finally {
			lock.unlock();
		}
	}

	/**
	 * Returns a new context identifier, given a description of the actual context.
	 * 
	 * @param description textual description of what context new messages will be used in
	 * @return a context id
	 */
	public int getContextId(String description) {
		lock.lock();
		try {
			return gtk_statusbar_get_context_id(this.pointer, description);
		}
		finally {
			lock.unlock();
		}
	}
}
