/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gobject_GType */

#ifndef _Included_org_java_gtk_gobject_GType
#define _Included_org_java_gtk_gobject_GType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gobject_GType
 * Method:    get_type
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gobject_GType_get_1type
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
