/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gobject_GObject */

#ifndef _Included_org_java_gtk_gobject_GObject
#define _Included_org_java_gtk_gobject_GObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gobject_GObject
 * Method:    add_toggle_ref
 * Signature: (JLorg/java_gtk/gobject/GObject;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gobject_GObject_add_1toggle_1ref
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_java_gtk_gobject_GObject
 * Method:    g_object_cleanup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gobject_GObject_g_1object_1cleanup
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
