/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Separator */

#ifndef _Included_org_java_gtk_gtk_Separator
#define _Included_org_java_gtk_gtk_Separator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Separator
 * Method:    gtk_separator_new
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Separator_gtk_1separator_1new
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
