/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_MenuShell */

#ifndef _Included_org_java_gtk_gtk_MenuShell
#define _Included_org_java_gtk_gtk_MenuShell
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_MenuShell
 * Method:    gtk_menu_shell_append
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_MenuShell_gtk_1menu_1shell_1append
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_java_gtk_gtk_MenuShell
 * Method:    gtk_menu_shell_prepend
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_MenuShell_gtk_1menu_1shell_1prepend
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_java_gtk_gtk_MenuShell
 * Method:    gtk_menu_shell_insert
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_MenuShell_gtk_1menu_1shell_1insert
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
