/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Toolbar */

#ifndef _Included_org_java_gtk_gtk_Toolbar
#define _Included_org_java_gtk_gtk_Toolbar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Toolbar
 * Method:    gtk_toolbar_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Toolbar_gtk_1toolbar_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_Toolbar
 * Method:    gtk_toolbar_set_style
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Toolbar_gtk_1toolbar_1set_1style
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_java_gtk_gtk_Toolbar
 * Method:    gtk_toolbar_insert
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Toolbar_gtk_1toolbar_1insert
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
