/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Label */

#ifndef _Included_org_java_gtk_gtk_Label
#define _Included_org_java_gtk_gtk_Label
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Label
 * Method:    gtk_label_new
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Label_gtk_1label_1new
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_java_gtk_gtk_Label
 * Method:    gtk_label_get_text
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_java_1gtk_gtk_Label_gtk_1label_1get_1text
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_Label
 * Method:    gtk_label_set_text
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Label_gtk_1label_1set_1text
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_java_gtk_gtk_Label
 * Method:    gtk_label_get_line_wrap
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_1gtk_gtk_Label_gtk_1label_1get_1line_1wrap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_Label
 * Method:    gtk_label_set_line_wrap
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Label_gtk_1label_1set_1line_1wrap
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
