/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_MessageDialog */

#ifndef _Included_org_java_gtk_gtk_MessageDialog
#define _Included_org_java_gtk_gtk_MessageDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_MessageDialog
 * Method:    gtk_message_dialog_new
 * Signature: (JIIILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_MessageDialog_gtk_1message_1dialog_1new
  (JNIEnv *, jclass, jlong, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
