/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_ComboBox */

#ifndef _Included_org_java_gtk_gtk_ComboBox
#define _Included_org_java_gtk_gtk_ComboBox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_ComboBox
 * Method:    gtk_combo_box_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_ComboBox_gtk_1combo_1box_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_ComboBox
 * Method:    gtk_combo_box_add_changed_event_handler
 * Signature: (JLorg/java_gtk/gtk/ComboBox/ChangedEventHandler;Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_ComboBox_gtk_1combo_1box_1add_1changed_1event_1handler
  (JNIEnv *, jclass, jlong, jobject, jclass);

#ifdef __cplusplus
}
#endif
#endif
