/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Alignment */

#ifndef _Included_org_java_gtk_gtk_Alignment
#define _Included_org_java_gtk_gtk_Alignment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Alignment
 * Method:    gtk_alignment_new
 * Signature: (FFFF)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Alignment_gtk_1alignment_1new
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_java_gtk_gtk_Alignment
 * Method:    gtk_alignment_set
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Alignment_gtk_1alignment_1set
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_java_gtk_gtk_Alignment
 * Method:    gtk_alignment_set_padding
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Alignment_gtk_1alignment_1set_1padding
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
