/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_IconView */

#ifndef _Included_org_java_gtk_gtk_IconView
#define _Included_org_java_gtk_gtk_IconView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_IconView
 * Method:    gtk_icon_view_new_with_model
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_IconView_gtk_1icon_1view_1new_1with_1model
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_IconView
 * Method:    gtk_icon_view_set_text_column
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_IconView_gtk_1icon_1view_1set_1text_1column
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_java_gtk_gtk_IconView
 * Method:    gtk_icon_view_set_pixbuf_column
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_IconView_gtk_1icon_1view_1set_1pixbuf_1column
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_java_gtk_gtk_IconView
 * Method:    gtk_icon_view_set_selection_mode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_IconView_gtk_1icon_1view_1set_1selection_1mode
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
