/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_MenuBar */

#ifndef _Included_org_java_gtk_gtk_MenuBar
#define _Included_org_java_gtk_gtk_MenuBar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_MenuBar
 * Method:    gtk_menu_bar_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_MenuBar_gtk_1menu_1bar_1new
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
