/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Grid */

#ifndef _Included_org_java_gtk_gtk_Grid
#define _Included_org_java_gtk_gtk_Grid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Grid
 * Method:    gtk_grid_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Grid_gtk_1grid_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_Grid
 * Method:    gtk_grid_attach
 * Signature: (JJIIII)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Grid_gtk_1grid_1attach
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint);

/*
 * Class:     org_java_gtk_gtk_Grid
 * Method:    gtk_grid_set_row_spacing
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Grid_gtk_1grid_1set_1row_1spacing
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_java_gtk_gtk_Grid
 * Method:    gtk_grid_get_row_spacing
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_java_1gtk_gtk_Grid_gtk_1grid_1get_1row_1spacing
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_Grid
 * Method:    gtk_grid_set_column_spacing
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Grid_gtk_1grid_1set_1column_1spacing
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_java_gtk_gtk_Grid
 * Method:    gtk_grid_get_column_spacing
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_java_1gtk_gtk_Grid_gtk_1grid_1get_1column_1spacing
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_Grid
 * Method:    gtk_grid_set_row_homogeneous
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Grid_gtk_1grid_1set_1row_1homogeneous
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_java_gtk_gtk_Grid
 * Method:    gtk_grid_get_row_homogeneous
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_1gtk_gtk_Grid_gtk_1grid_1get_1row_1homogeneous
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_Grid
 * Method:    gtk_grid_set_column_homogeneous
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Grid_gtk_1grid_1set_1column_1homogeneous
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_java_gtk_gtk_Grid
 * Method:    gtk_grid_get_column_homogeneous
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_1gtk_gtk_Grid_gtk_1grid_1get_1column_1homogeneous
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
