/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_TreeModel */

#ifndef _Included_org_java_gtk_gtk_TreeModel
#define _Included_org_java_gtk_gtk_TreeModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_TreeModel
 * Method:    gtk_tree_model_get_long
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_TreeModel_gtk_1tree_1model_1get_1long
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_java_gtk_gtk_TreeModel
 * Method:    gtk_tree_model_get_string
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_java_1gtk_gtk_TreeModel_gtk_1tree_1model_1get_1string
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
