/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_ScrolledWindow */

#ifndef _Included_org_java_gtk_gtk_ScrolledWindow
#define _Included_org_java_gtk_gtk_ScrolledWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_ScrolledWindow
 * Method:    gtk_scrolled_window_new
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_ScrolledWindow_gtk_1scrolled_1window_1new
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_java_gtk_gtk_ScrolledWindow
 * Method:    gtk_scrolled_window_set_policy
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_ScrolledWindow_gtk_1scrolled_1window_1set_1policy
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_java_gtk_gtk_ScrolledWindow
 * Method:    gtk_scrolled_window_set_shadow_type
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_ScrolledWindow_gtk_1scrolled_1window_1set_1shadow_1type
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
