/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_AboutDialog */

#ifndef _Included_org_java_gtk_gtk_AboutDialog
#define _Included_org_java_gtk_gtk_AboutDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_AboutDialog
 * Method:    gtk_about_dialog_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_AboutDialog_gtk_1about_1dialog_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_AboutDialog
 * Method:    gtk_about_dialog_get_program_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_java_1gtk_gtk_AboutDialog_gtk_1about_1dialog_1get_1program_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_AboutDialog
 * Method:    gtk_about_dialog_set_program_name
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_AboutDialog_gtk_1about_1dialog_1set_1program_1name
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_java_gtk_gtk_AboutDialog
 * Method:    gtk_about_dialog_get_version
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_java_1gtk_gtk_AboutDialog_gtk_1about_1dialog_1get_1version
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_AboutDialog
 * Method:    gtk_about_dialog_set_version
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_AboutDialog_gtk_1about_1dialog_1set_1version
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_java_gtk_gtk_AboutDialog
 * Method:    gtk_about_dialog_get_copyright
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_java_1gtk_gtk_AboutDialog_gtk_1about_1dialog_1get_1copyright
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_AboutDialog
 * Method:    gtk_about_dialog_set_copyright
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_AboutDialog_gtk_1about_1dialog_1set_1copyright
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_java_gtk_gtk_AboutDialog
 * Method:    gtk_about_dialog_get_comments
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_java_1gtk_gtk_AboutDialog_gtk_1about_1dialog_1get_1comments
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_AboutDialog
 * Method:    gtk_about_dialog_set_comments
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_AboutDialog_gtk_1about_1dialog_1set_1comments
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_java_gtk_gtk_AboutDialog
 * Method:    gtk_about_dialog_get_website
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_java_1gtk_gtk_AboutDialog_gtk_1about_1dialog_1get_1website
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_AboutDialog
 * Method:    gtk_about_dialog_set_website
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_AboutDialog_gtk_1about_1dialog_1set_1website
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_java_gtk_gtk_AboutDialog
 * Method:    gtk_about_dialog_get_logo
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_AboutDialog_gtk_1about_1dialog_1get_1logo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_AboutDialog
 * Method:    gtk_about_dialog_set_logo
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_AboutDialog_gtk_1about_1dialog_1set_1logo
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
