/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_TreeViewColumn */

#ifndef _Included_org_java_gtk_gtk_TreeViewColumn
#define _Included_org_java_gtk_gtk_TreeViewColumn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_TreeViewColumn
 * Method:    gtk_tree_view_column_pack_start
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_TreeViewColumn_gtk_1tree_1view_1column_1pack_1start
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_java_gtk_gtk_TreeViewColumn
 * Method:    gtk_tree_view_column_pack_end
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_TreeViewColumn_gtk_1tree_1view_1column_1pack_1end
  (JNIEnv *, jclass, jlong, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
