/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_ImageMenuItem */

#ifndef _Included_org_java_gtk_gtk_ImageMenuItem
#define _Included_org_java_gtk_gtk_ImageMenuItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_ImageMenuItem
 * Method:    gtk_image_menu_item_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_ImageMenuItem_gtk_1image_1menu_1item_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_ImageMenuItem
 * Method:    gtk_image_menu_item_new_with_label
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_ImageMenuItem_gtk_1image_1menu_1item_1new_1with_1label
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_java_gtk_gtk_ImageMenuItem
 * Method:    gtk_image_menu_item_new_with_mnemonic
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_ImageMenuItem_gtk_1image_1menu_1item_1new_1with_1mnemonic
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_java_gtk_gtk_ImageMenuItem
 * Method:    gtk_image_menu_item_new_from_stock
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_ImageMenuItem_gtk_1image_1menu_1item_1new_1from_1stock
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
