/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_AccelGroup */

#ifndef _Included_org_java_gtk_gtk_AccelGroup
#define _Included_org_java_gtk_gtk_AccelGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_AccelGroup
 * Method:    gtk_accel_group_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_AccelGroup_gtk_1accel_1group_1new
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
