/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Dialog */

#ifndef _Included_org_java_gtk_gtk_Dialog
#define _Included_org_java_gtk_gtk_Dialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Dialog
 * Method:    gtk_dialog_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Dialog_gtk_1dialog_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_Dialog
 * Method:    gtk_dialog_run
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_java_1gtk_gtk_Dialog_gtk_1dialog_1run
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
