/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_TreeIterator */

#ifndef _Included_org_java_gtk_gtk_TreeIterator
#define _Included_org_java_gtk_gtk_TreeIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_TreeIterator
 * Method:    gtk_tree_iter_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_TreeIterator_gtk_1tree_1iter_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_TreeIterator
 * Method:    gtk_tree_iter_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_TreeIterator_gtk_1tree_1iter_1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
