/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Adjustment */

#ifndef _Included_org_java_gtk_gtk_Adjustment
#define _Included_org_java_gtk_gtk_Adjustment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Adjustment
 * Method:    gtk_adjustment_new
 * Signature: (DDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Adjustment_gtk_1adjustment_1new
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
