/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Dialog_DialogFlags */

#ifndef _Included_org_java_gtk_gtk_Dialog_DialogFlags
#define _Included_org_java_gtk_gtk_Dialog_DialogFlags
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
