/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_TreeView */

#ifndef _Included_org_java_gtk_gtk_TreeView
#define _Included_org_java_gtk_gtk_TreeView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_TreeView
 * Method:    gtk_tree_view_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_TreeView_gtk_1tree_1view_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_TreeView
 * Method:    gtk_tree_view_set_headers_visible
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_TreeView_gtk_1tree_1view_1set_1headers_1visible
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_java_gtk_gtk_TreeView
 * Method:    gtk_tree_view_set_model
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_TreeView_gtk_1tree_1view_1set_1model
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_java_gtk_gtk_TreeView
 * Method:    gtk_tree_view_get_model
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_TreeView_gtk_1tree_1view_1get_1model
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_TreeView
 * Method:    gtk_tree_view_append_column
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_java_1gtk_gtk_TreeView_gtk_1tree_1view_1append_1column
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_java_gtk_gtk_TreeView
 * Method:    gtk_tree_view_get_selection
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_TreeView_gtk_1tree_1view_1get_1selection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
