/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_ScrolledWindow_PolicyType */

#ifndef _Included_org_java_gtk_gtk_ScrolledWindow_PolicyType
#define _Included_org_java_gtk_gtk_ScrolledWindow_PolicyType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
