/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_AccelMap */

#ifndef _Included_org_java_gtk_gtk_AccelMap
#define _Included_org_java_gtk_gtk_AccelMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_AccelMap
 * Method:    gtk_accel_map_add_entry
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_AccelMap_gtk_1accel_1map_1add_1entry
  (JNIEnv *, jclass, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
