/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_CellRendererText */

#ifndef _Included_org_java_gtk_gtk_CellRendererText
#define _Included_org_java_gtk_gtk_CellRendererText
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_CellRendererText
 * Method:    gtk_cell_renderer_text_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_CellRendererText_gtk_1cell_1renderer_1text_1new
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
