/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Entry */

#ifndef _Included_org_java_gtk_gtk_Entry
#define _Included_org_java_gtk_gtk_Entry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Entry
 * Method:    gtk_entry_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Entry_gtk_1entry_1new
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
