/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Frame */

#ifndef _Included_org_java_gtk_gtk_Frame
#define _Included_org_java_gtk_gtk_Frame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Frame
 * Method:    gtk_frame_new
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Frame_gtk_1frame_1new
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_java_gtk_gtk_Frame
 * Method:    gtk_frame_get_label
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_java_1gtk_gtk_Frame_gtk_1frame_1get_1label
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_Frame
 * Method:    gtk_frame_set_label
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Frame_gtk_1frame_1set_1label
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_java_gtk_gtk_Frame
 * Method:    gtk_frame_get_shadow_type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_java_1gtk_gtk_Frame_gtk_1frame_1get_1shadow_1type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_Frame
 * Method:    gtk_frame_set_shadow_type
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Frame_gtk_1frame_1set_1shadow_1type
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
