/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Image */

#ifndef _Included_org_java_gtk_gtk_Image
#define _Included_org_java_gtk_gtk_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Image
 * Method:    gtk_image_new_from_file
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_Image_gtk_1image_1new_1from_1file
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
