/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_TreeSelection */

#ifndef _Included_org_java_gtk_gtk_TreeSelection
#define _Included_org_java_gtk_gtk_TreeSelection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_TreeSelection
 * Method:    gtk_tree_selection_get_selected
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_TreeSelection_gtk_1tree_1selection_1get_1selected
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_TreeSelection
 * Method:    gtk_tree_selection_add_changed_event_handler
 * Signature: (JLorg/java_gtk/gtk/TreeSelection/ChangedEventHandler;Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_TreeSelection_gtk_1tree_1selection_1add_1changed_1event_1handler
  (JNIEnv *, jclass, jlong, jobject, jclass);

#ifdef __cplusplus
}
#endif
#endif
