/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Gtk */

#ifndef _Included_org_java_gtk_gtk_Gtk
#define _Included_org_java_gtk_gtk_Gtk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_Gtk
 * Method:    gtk_init
 * Signature: (Ljava/lang/Object;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Gtk_gtk_1init
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     org_java_gtk_gtk_Gtk
 * Method:    gtk_init_check
 * Signature: (Ljava/lang/Object;[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_1gtk_gtk_Gtk_gtk_1init_1check
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     org_java_gtk_gtk_Gtk
 * Method:    gtk_main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Gtk_gtk_1main
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_Gtk
 * Method:    gtk_main_iteration_do
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_1gtk_gtk_Gtk_gtk_1main_1iteration_1do
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_java_gtk_gtk_Gtk
 * Method:    gtk_events_pending
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_1gtk_gtk_Gtk_gtk_1events_1pending
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_Gtk
 * Method:    gtk_main_quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Gtk_gtk_1main_1quit
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_Gtk
 * Method:    g_signal_handler_disconnect
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_Gtk_g_1signal_1handler_1disconnect
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
