/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_ToggleButton */

#ifndef _Included_org_java_gtk_gtk_ToggleButton
#define _Included_org_java_gtk_gtk_ToggleButton
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_ToggleButton
 * Method:    gtk_toggle_button_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_ToggleButton_gtk_1toggle_1button_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_java_gtk_gtk_ToggleButton
 * Method:    gtk_toggle_button_new_with_label
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_ToggleButton_gtk_1toggle_1button_1new_1with_1label
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_java_gtk_gtk_ToggleButton
 * Method:    gtk_toggle_button_new_with_mnemonic
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_ToggleButton_gtk_1toggle_1button_1new_1with_1mnemonic
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_java_gtk_gtk_ToggleButton
 * Method:    gtk_toggle_button_set_active
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_ToggleButton_gtk_1toggle_1button_1set_1active
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_java_gtk_gtk_ToggleButton
 * Method:    gtk_toggle_button_get_active
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_1gtk_gtk_ToggleButton_gtk_1toggle_1button_1get_1active
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
