/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_Label_Justification */

#ifndef _Included_org_java_gtk_gtk_Label_Justification
#define _Included_org_java_gtk_gtk_Label_Justification
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
