/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_TreeViewTextColumn */

#ifndef _Included_org_java_gtk_gtk_TreeViewTextColumn
#define _Included_org_java_gtk_gtk_TreeViewTextColumn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_TreeViewTextColumn
 * Method:    gtk_tree_view_text_column_new
 * Signature: (Ljava/lang/String;JI)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_TreeViewTextColumn_gtk_1tree_1view_1text_1column_1new
  (JNIEnv *, jclass, jstring, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
