/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_TreeModel */

#ifndef _Included_org_java_gtk_gtk_TreeModel
#define _Included_org_java_gtk_gtk_TreeModel
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
