/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_ListStore */

#ifndef _Included_org_java_gtk_gtk_ListStore
#define _Included_org_java_gtk_gtk_ListStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_ListStore
 * Method:    gtk_list_store_new
 * Signature: (I[J)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_ListStore_gtk_1list_1store_1new
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     org_java_gtk_gtk_ListStore
 * Method:    gtk_list_store_append
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_ListStore_gtk_1list_1store_1append
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_java_gtk_gtk_ListStore
 * Method:    gtk_list_store_remove
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_1gtk_gtk_ListStore_gtk_1list_1store_1remove
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_java_gtk_gtk_ListStore
 * Method:    gtk_list_store_clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_ListStore_gtk_1list_1store_1clear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gtk_ListStore
 * Method:    gtk_list_store_set_string
 * Signature: (JJILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_ListStore_gtk_1list_1store_1set_1string
  (JNIEnv *, jclass, jlong, jlong, jint, jstring);

/*
 * Class:     org_java_gtk_gtk_ListStore
 * Method:    gtk_list_store_set_pixbuf
 * Signature: (JJIJ)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gtk_ListStore_gtk_1list_1store_1set_1pixbuf
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
