/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gtk_DrawingArea */

#ifndef _Included_org_java_gtk_gtk_DrawingArea
#define _Included_org_java_gtk_gtk_DrawingArea
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gtk_DrawingArea
 * Method:    gtk_drawing_area_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gtk_DrawingArea_gtk_1drawing_1area_1new
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
