/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_glib_Timer */

#ifndef _Included_org_java_gtk_glib_Timer
#define _Included_org_java_gtk_glib_Timer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_glib_Timer
 * Method:    g_timer_new
 * Signature: (ILorg/java_gtk/glib/Timer/TimerHandler;J)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_glib_Timer_g_1timer_1new
  (JNIEnv *, jclass, jint, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
