/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_glib_Timer_TimerHandler */

#ifndef _Included_org_java_gtk_glib_Timer_TimerHandler
#define _Included_org_java_gtk_glib_Timer_TimerHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
