/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gdk_EventButton */

#ifndef _Included_org_java_gtk_gdk_EventButton
#define _Included_org_java_gtk_gdk_EventButton
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gdk_EventButton
 * Method:    gtk_event_button_get_x_root
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_java_1gtk_gdk_EventButton_gtk_1event_1button_1get_1x_1root
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gdk_EventButton
 * Method:    gtk_event_button_get_y_root
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_java_1gtk_gdk_EventButton_gtk_1event_1button_1get_1y_1root
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gdk_EventButton
 * Method:    gtk_event_button_get_time
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gdk_EventButton_gtk_1event_1button_1get_1time
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gdk_EventButton
 * Method:    gtk_event_button_get_button
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_java_1gtk_gdk_EventButton_gtk_1event_1button_1get_1button
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
