/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gdk_Event */

#ifndef _Included_org_java_gtk_gdk_Event
#define _Included_org_java_gtk_gdk_Event
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gdk_Event
 * Method:    gtk_event_get_type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_java_1gtk_gdk_Event_gtk_1event_1get_1type
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
