/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gdk_EventConfigure */

#ifndef _Included_org_java_gtk_gdk_EventConfigure
#define _Included_org_java_gtk_gdk_EventConfigure
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gdk_EventConfigure
 * Method:    gtk_event_configure_get_x
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_java_1gtk_gdk_EventConfigure_gtk_1event_1configure_1get_1x
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gdk_EventConfigure
 * Method:    gtk_event_configure_get_y
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_java_1gtk_gdk_EventConfigure_gtk_1event_1configure_1get_1y
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gdk_EventConfigure
 * Method:    gtk_event_configure_get_width
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_java_1gtk_gdk_EventConfigure_gtk_1event_1configure_1get_1width
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_java_gtk_gdk_EventConfigure
 * Method:    gtk_event_configure_get_height
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_java_1gtk_gdk_EventConfigure_gtk_1event_1configure_1get_1height
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
