/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_gtk_gdk_RGBA */

#ifndef _Included_org_java_gtk_gdk_RGBA
#define _Included_org_java_gtk_gdk_RGBA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_gtk_gdk_RGBA
 * Method:    gdk_rgba_new
 * Signature: (DDDD)J
 */
JNIEXPORT jlong JNICALL Java_org_java_1gtk_gdk_RGBA_gdk_1rgba_1new
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_java_gtk_gdk_RGBA
 * Method:    gdk_rgba_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_java_1gtk_gdk_RGBA_gdk_1rgba_1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
