/* 
 * Copyright (c) 2012 - 2013, JavaGTK and Bill Hull
 *
 * Permission to use, copy, modify, and/or distribute this software
 * for any purpose with or without fee is hereby granted, provided 
 * that the above copyright notice and this permission notice appear 
 * in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL 
 * WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED 
 * WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE 
 * AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 * DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 
 * OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER 
 * TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR 
 * PERFORMANCE OF THIS SOFTWARE.
 */

package org.java_gtk.gdk;

public enum ModifierType {
	SHIFT_MASK,
	LOCK_MASK,
	CONTROL_MASK,
	MOD1_MASK,
	MOD2_MASK,
	MOD3_MASK,
	MOD4_MASK,
	MOD5_MASK,
	BUTTON1_MASK,
	BUTTON2_MASK,
	BUTTON3_MASK,
	BUTTON4_MASK,
	BUTTON5_MASK,

	MODIFIER_RESERVED_13_MASK,
	MODIFIER_RESERVED_14_MASK,
	MODIFIER_RESERVED_15_MASK,
	MODIFIER_RESERVED_16_MASK,
	MODIFIER_RESERVED_17_MASK,
	MODIFIER_RESERVED_18_MASK,
	MODIFIER_RESERVED_19_MASK,
	MODIFIER_RESERVED_20_MASK,
	MODIFIER_RESERVED_21_MASK,
	MODIFIER_RESERVED_22_MASK,
	MODIFIER_RESERVED_23_MASK,
	MODIFIER_RESERVED_24_MASK,
	MODIFIER_RESERVED_25_MASK,
			  
	SUPER_MASK,
	HYPER_MASK,
	META_MASK,
			  
	MODIFIER_RESERVED_29_MASK,

	RELEASE_MASK;
	
    public int getValue(){
        return 1 << this.ordinal();
    } 
}
